public class Main {

    public static void main(String[] args) {

        String filename = "";
        String fake = "";
        double rating = 0.0;
        int stars = 0;

        /*
         * Activity 1 - Introduction
         * Since the sentimentVal method is a static method, include the class name when calling it
         * and since it returns a value, call it in an assignment statement
         * e.g: rating = Review.sentimentVal("awesome");
         * Print the returned value to see the result
         */

//        rating = Review.sentimentVal("awesome");
//        System.out.println(rating);
//
//        // TODO - Activity 1 Step 2
//
//        rating = Review.sentimentVal("happily");
//        System.out.println(rating);
//
//        rating = Review.sentimentVal("terrible");
//        System.out.println(rating);
//
//        rating = Review.sentimentVal("cold");
//        System.out.println(rating);
//
//        rating = Review.sentimentVal("static");
//        System.out.println(rating);
//
//        rating = Review.sentimentVal("negative");
//        System.out.println(rating);
//
//        rating = Review.sentimentVal("pink");
//        System.out.println(rating);


        /*
         * Activity 2 - Sentiment Value and Star Ratings
         * Write the methods totalSentiment (step 1) and starRating (step 3)
         * in Review.java.
         * Then uncomment the lines below to test those methods
         * This uses the 2 sample review files, SimpleReview.txt and 26WestReview.txt.
         * Create your own review file to test if you'd like
         */

        System.out.println(Review.totalSentiment("26WestReview.txt"));

//        filename = "SimpleReview.txt";
//        rating = Review.totalSentiment(filename);
//        stars = Review.starRating(filename);
//        System.out.println("Review " + filename + ": " + rating + "\t(" + stars + " stars)\n");
//
//        filename = "26WestReview.txt";
//        rating = Review.totalSentiment(filename);
//        stars = Review.starRating(filename);
//        System.out.println("Review " + filename + ": " + rating + "\t(" + stars + " stars)\n");

        /*
         * Activity 3 - Autogenerated Review
         * Edit the file SimpleReview2.txt as described in the instructions (add "*"
         * before each adjective in the review).
         * Implement the method fakeReview in Review.java
         * Then uncomment the lines below to test that method
         *
         * Activity 4 - Create negative or positive review
         * Edit the fakeReview method in Review.java to always generate a positive (or negative) review
         */
        filename = "SimpleReview2.txt";
        fake = Review.fakeReview(filename);
        System.out.println("*** Fake Review ***");
        System.out.println(fake);
        System.out.println();
    }
}